### ISSUE TITLE
More specific instructions for setting up the eval

### ISSUE THREAD

**Issue by ftyers** [Cyvhee/SemEval2018-Task3#1]
It might be good to have a description of how to get the same numbers from the example code and from the evaluation script. Here is a short list:

```
$ git clone https://github.com/Cyvhee/SemEval2018-Task3.git
$ cd SemEval2018-Task3/evaluation
$ mkdir res ref
$ cd ../benchmark_system
$ python3 example.py 
[[0, 1923], [1, 1911]]
F1-score Task A 0.626344086022
$ cd ../evaluation
$ cat ../benchmark_system/SemEval2018-T4-train-taskA.txt | cut -f2 | grep '[0-9]' > ref/goldstandard_train_A.txt 
$ cp ../benchmark_system/predictions-taskA.txt res/
$ python3 evaluate.py . .
$ cat scores.txt 
Accuracy:0.6374543557642149
Precision:0.6440022111663902
Recall:0.6096284667713239
F1-score:0.6263440860215053
```

**Comment by Cyvhee** [comment]
Hi

Sorry for the late response!
The evaluation.py script is automatically run on CodaLab when participants upload their submission. It is posted on GitHub to show participants how scores will be calculated in the evaluation period. The benchmark system can (but does not have to!) serve as a basic script to start developing an irony detection system. The script outputs F1-score to evaluate the system performance. Participants can add metrics like accuracy, precision and recall as well, but these just serve to give them an indication of how well their system works. The official scores will be calculated automatically when uploading their predictions via CodaLab.

Let me know if this does not answer your questions.

Kind regards
Cynthia
