### ISSUE TITLE
Size of trial data

### ISSUE THREAD

**Issue by ftyers** [Cyvhee/SemEval2018-Task3#2]
Is it right that there is only 10 lines of trial data or was this a mistake in the upload ?

**Comment by Cyvhee** [comment]
Yes, that is right. The trial data was meant to try uploading a submission file at CodaLab.

**Comment by ftyers** [comment]
Ok, thanks! Perhaps a note could be added that this data is only supposed to be used for testing the CodaLab stuff and for parameter tuning and stuff, use cross-validation ? It could be that it's obvious to everyone, but often people think about 'trial' as like 'dev' data.

**Comment by Cyvhee** [comment]
You are right, I added a short note on this in the README ;-).

**Comment by ftyers** [comment]
Thanks! :)
